version: '3.8'
services:
  #auth-service:
    #build:
     # context: ./auth_service
      #dockerfile: Dockerfile
    #image: auth_service
    #environment:
     # - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth:5432/authentication_db
      #- SPRING_DATASOURCE_USERNAME=postgres
     # - SPRING_DATASOURCE_PASSWORD=DBPASSWORD
    #depends_on:
     # - db-auth
    #ports:
     # - "8008:8080"

  #chat_service:
  #  build:
  #    context: ./chat_service
  #    dockerfile: Dockerfile
  #  image: chat_service
  #  ports:
   #   - "8000:8080"

  db-auth:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBPASSWORD
    ports:
      - "5435:5432"

  db-message:
    image: mongo:latest
    container_name: db-message
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
    ports:
      - "27017:27017"
    volumes:
      - message_db_data:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

volumes:
  message_db_data: