server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: chat-service
          uri: ws://localhost:8081
          predicates:
            - Path=/ws/**

        - id: message-service
          uri: http://localhost:8082
          predicates:
            - Path=/message/**

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**

        - id: file_storage_service
          uri: http://localhost:8084
          predicates:
            - Path=/**